when@dev: &dev
    hautelook_alice:
        fixtures_path:
            - fixtures
            - fixtures/user
            - fixtures/skill
            - fixtures/faction
            - fixtures/position
            - fixtures/special_rules
            - fixtures/team

when@test: *dev
